<?php

declare(strict_types=1);

/**
 * Content aligned with IPECS corporate profile — Our impacts (PDF).
 * impact_rows: [indicator, scale/reach, client/funder] → merged on the page as “Achievement”.
 */
return [
    'hero_tagline' => 'IPECS Consulting Pvt. Ltd. | Transforming vision into excellence',
    'hero_sub' => 'Established: 2012 | Karachi, Pakistan | 14 years of delivering excellence',
    'consolidated' => [
        ['Years of operation', '14 years (2012–2026)'],
        ['Total projects delivered', '31+ major projects and programmes'],
        ['Cumulative contract portfolio', 'PKR 2.55 billion+'],
        ['Districts covered', '34+ districts in Sindh, Balochistan and KPK'],
        ['Provinces covered', 'Sindh, Balochistan, Khyber Pakhtunkhwa'],
        ['Team strength', '117+ multidisciplinary professionals'],
        ['Technical sectors', '9 specialised sectors'],
        ['Schools supported', '160+ schools assessed, supported and strengthened'],
        ['School infrastructure projects', '123 school buildings designed, procured and supervised'],
        ['School WASH facilities', '489 facilities rehabilitated'],
        ['Water supply schemes', '650+ schemes across 13 Sindh districts'],
        ['Villages assessed for WASH', '5,200 villages across 13 Sindh districts'],
        ['Solar energy beneficiaries', '200,000 families across 30 Sindh districts'],
        ['Teachers trained', '1,200+ teachers across Sindh and KPK'],
        ['MHM kits distributed', '10,000 kits across 40 schools and communities'],
        ['Livelihoods villages monitored', '382 villages in Gwadar and Lasbela'],
        ['Household surveys conducted', '14,000+ households across Sindh and Balochistan'],
        ['Evaluations and research studies', '31+ independent evaluations and research studies'],
    ],
    'portfolio_rows' => [
        ['Education systems strengthening and skills development', 'PKR 350+ million'],
        ['Institutional governance, policy and public sector reform', 'PKR 200+ million'],
        ['Engineering, infrastructure and urban development', 'PKR 350+ million'],
        ['Climate-smart environment, energy, agriculture and resilience', 'PKR 280+ million'],
        ['Water, sanitation and integrated urban services', 'PKR 420+ million'],
        ['Technology, digital transformation and smart systems', 'PKR 150+ million'],
        ['Social inclusion, gender equity, livelihoods and rural development', 'PKR 320+ million'],
        ['Monitoring, evaluation, learning and impact advisory', 'PKR 280+ million'],
        ['Health systems strengthening and nutrition', 'PKR 200+ million'],
    ],
    'portfolio_total' => 'PKR 2.55 billion+',
    'geo_rows' => [
        ['Sindh', '29 districts', 'Karachi, Hyderabad, Sukkur, Larkana, Thatta, Badin, Tharparkar, Umerkot, Sanghar, Mirpurkhas, Nawabshah, Naushahro Feroze, Khairpur, Ghotki, Jacobabad, Kashmore, Shikarpur, Dadu, Matiari, Tando Allahyar, Tando Mohammad Khan, Sujawal, Kambar Shahdadkot, Jamshoro, and others'],
        ['Balochistan', '3 districts', 'Quetta, Gwadar, Lasbela'],
        ['Khyber Pakhtunkhwa', '2 districts', 'Upper Dir, Swat'],
        ['Total', '34+ districts', 'Urban, peri-urban and remote rural'],
    ],
    'client_ecosystem' => [
        ['Multilateral banks', 'World Bank, Asian Development Bank, AIIB, Islamic Development Bank'],
        ['United Nations', 'UNDP, UNICEF, FAO, UNESCO, IFAD, USAID'],
        ['Government of Sindh', 'P&amp;D Dept., SSPA, LGD, Energy Dept., Agriculture Dept., PHED'],
        ['Government of Balochistan', 'Secondary Education Department'],
        ['Government of Pakistan', 'Ministry of Education, Ministry of Climate Change'],
        ['International NGOs', 'Save the Children, Oxfam, Concern Worldwide, ACTED, HEKS/EPER, Kindernothilfe, KOICA, WWF'],
        ['Private sector and CSR', 'Pakistan Petroleum Limited, PPAF, Indus Valley School System'],
    ],
    'quote' => 'Our impact is not measured in contracts alone. It is measured in lives improved, institutions strengthened, communities empowered, and systems built to endure.',
    'sectors' => [
        'education' => [
            'tab' => 'Education',
            'n' => 1,
            'title' => 'Education systems strengthening and skills development',
            'intro' => 'Strengthening public education systems, enhancing human capital, and improving learning outcomes across Pakistan from early childhood through TVET and higher education.',
            'page' => 'sector-education.php',
            'impact_rows' => [
                ['Schools assessed, supported and strengthened', '160+ schools in Sindh and KPK', 'World Bank, GPE, UNICEF'],
                ['School infrastructure projects', '123 projects designed, procured and supervised', 'World Bank and GPE'],
                ['School WASH facilities rehabilitated', '489 facilities rehabilitated', 'UNICEF, Dadu and NF'],
                ['Teachers trained', '1,200+ teachers trained', 'Save the Children, Kindernothilfe'],
                ['SMCs strengthened', '160+ schools in coastal and interior Sindh', 'World Bank, GPE'],
                ['PPP bidding packages developed', '123 schools with girls education focus', 'GPE and European Commission'],
                ['Sector evaluations conducted', 'Multiple studies delivered', 'World Bank, UNESCO, UNICEF'],
            ],
            'contract_value' => 'PKR 350+ million',
            'key_partners' => 'Government of Balochistan, Federal Ministry of Education, UNESCO Pakistan, UNICEF Pakistan, Save the Children, Kindernothilfe Germany, PPAF, Indus Valley School System',
        ],
        'governance' => [
            'tab' => 'Governance',
            'n' => 2,
            'title' => 'Institutional governance, policy and public sector reform',
            'intro' => 'Improving how public institutions function, make decisions, allocate resources, deliver services, and remain accountable to citizens, aligned with SDG 16.',
            'page' => 'sector-governance.php',
            'impact_rows' => [
                ['PPP transaction packages developed', '5 comprehensive packages', 'Government of Sindh, World Bank, ADB'],
                ['Social protection feasibility studies', '3 major studies', 'Government of Sindh and World Bank'],
                ['Institutional reform engagements', '7 engagements at federal, provincial and local level', 'World Bank, ADB'],
                ['GRM systems designed and operationalised', '10+ programmes', 'World Bank, UNDP, IFAD'],
                ['Conditional cash transfer framework', '5 Sindh districts for women agricultural workers', 'Government of Sindh and World Bank'],
                ['Social safety net evaluations', '7 districts, baseline and endline', 'Oxfam International'],
            ],
            'contract_value' => 'PKR 200+ million',
            'key_partners' => 'P&amp;D Department Government of Sindh, Sindh Social Protection Authority, ADB, Oxfam International',
        ],
        'infrastructure' => [
            'tab' => 'Infrastructure',
            'n' => 3,
            'title' => 'Engineering, infrastructure and urban development',
            'intro' => 'Full infrastructure lifecycle delivery from feasibility through design, procurement, supervision and O&amp;M, supporting resilient growth and sustainable urbanisation.',
            'page' => 'sector-infrastructure.php',
            'impact_rows' => [
                ['School infrastructure projects', '123 projects designed, procured and supervised', 'Save the Children, World Bank'],
                ['School WASH facilities rehabilitated', '489 facilities', 'UNICEF, Dadu and NF'],
                ['Groundwater monitoring systems', '10 borehole piezometers installed', 'Green Climate Fund and FAO'],
                ['Katchi abadi feasibility study', '17 katchi abadis in Sukkur', 'ADB and SCIP'],
                ['Solar-powered WASH systems', 'Hyderabad and Mirpurkhas', 'KOICA Pakistan'],
                ['Water supply schemes designed', '650 schemes in 13 Sindh districts', 'World Bank and DFID MSAN'],
                ['Drainage and sewerage schemes', '400 schemes in 13 Sindh districts', 'World Bank and DFID MSAN'],
                ['School WASH interventions designed', '2,600 interventions in 13 Sindh districts', 'World Bank and DFID MSAN'],
            ],
            'contract_value' => 'PKR 350+ million',
            'key_partners' => 'UNICEF, KOICA, Save the Children, PPL CSR, ADB, LGD Government of Sindh, FAO',
        ],
        'climate' => [
            'tab' => 'Climate',
            'n' => 4,
            'title' => 'Climate-smart environment, energy, agriculture and resilience',
            'intro' => 'Translating climate commitments into actionable, scalable interventions aligned with Pakistan\'s NDCs, National Climate Change Policy, and the Paris Agreement.',
            'page' => 'sector-climate.php',
            'impact_rows' => [
                ['Solar energy beneficiaries monitored', '200,000 families in 30 Sindh districts', 'World Bank SSEP'],
                ['Sustainable land management programme', '22-month implementation in 5 Sindh districts', 'UNDP and Ministry of Climate Change'],
                ['Groundwater monitoring boreholes', '10 boreholes in Sanghar and Umerkot', 'Green Climate Fund and FAO'],
                ['District land-use plans', '5 Sindh districts developed and operationalised', 'UNDP SLMP-II'],
                ['Community DRR programmes', 'Jacobabad, Kashmore and Shikarpur', 'ACTED'],
                ['ESMPs prepared and implemented', 'Multiple programmes across Sindh', 'World Bank, ADB, UNDP'],
            ],
            'contract_value' => 'PKR 280+ million',
            'key_partners' => 'Energy Department Government of Sindh, UNDP Pakistan, Ministry of Climate Change, FAO, ACTED',
        ],
        'wash' => [
            'tab' => 'WASH',
            'n' => 5,
            'title' => 'Water, sanitation and integrated urban services',
            'intro' => 'Integrated WASH solutions improving public health, environmental sustainability, and quality of life aligned with SDG 6 across rural, peri-urban, and urban Pakistan.',
            'page' => 'sector-wash.php',
            'impact_rows' => [
                ['Water supply schemes designed', '650 schemes in 13 Sindh districts', 'World Bank and DFID MSAN'],
                ['Drainage and sewerage schemes designed', '400 schemes in 13 Sindh districts', 'World Bank and DFID MSAN'],
                ['School WASH interventions designed', '2,600 interventions in 13 Sindh districts', 'World Bank and DFID MSAN'],
                ['Villages assessed for WASH', '5,200 villages in 13 Sindh districts', 'World Bank Saaf Suthro Sindh'],
                ['School WASH facilities rehabilitated', '489 government primary schools in Dadu and NF', 'UNICEF Pakistan'],
                ['Solar-powered WASH systems', 'Hyderabad and Mirpurkhas informal settlements', 'KOICA Pakistan'],
                ['Sewerage schemes for rehabilitation', '500 to 600 schemes in 13 Sindh districts', 'World Bank and DFID MSAN'],
                ['Community WASH institutions formed', 'Hundreds of VDCs, WASH and O&amp;M committees', 'World Bank, UNICEF, USAID'],
            ],
            'contract_value' => 'PKR 420+ million',
            'key_partners' => 'LGD Government of Sindh, UNICEF, KOICA, USAID, World Bank, AAP Government of Sindh',
        ],
        'technology' => [
            'tab' => 'Digital',
            'n' => 6,
            'title' => 'Technology, digital transformation and smart systems',
            'intro' => 'Technology as a strategic enabler of institutional performance, deploying digital tools in service of governance, accountability, and community empowerment objectives.',
            'page' => 'sector-technology.php',
            'impact_rows' => [
                ['CATI household survey', '14,000 households in Sindh and Balochistan', 'UNDP 4RF Flood Recovery'],
                ['Socioeconomic survey', 'Old Karachi areas using tablet and mobile data collection', 'World Bank CLICK'],
                ['Digital monitoring systems', 'KoboToolbox-based systems in 30 districts', 'World Bank SSEP'],
                ['Digital GRM systems', 'Multi-tier GRM with complaint tracking dashboards', 'World Bank SSEP'],
                ['MIS systems deployed', '5+ major programmes', 'World Bank, UNDP, ADB'],
                ['Data analysis platforms', 'SPSS, Stata, R and Excel across multiple evaluations', 'World Bank, UNDP, IFAD'],
            ],
            'contract_value' => 'PKR 150+ million',
            'key_partners' => 'UNDP Pakistan, World Bank CLICK, SSEP, MSAN, Energy Department Government of Sindh, LGD Government of Sindh',
        ],
        'inclusion' => [
            'tab' => 'Inclusion',
            'n' => 7,
            'title' => 'Social inclusion, gender equity, livelihoods and rural development',
            'intro' => 'People-centred solutions addressing poverty, inequality, and vulnerability, placing gender equity and social inclusion at the core of all programming.',
            'page' => 'sector-inclusion.php',
            'impact_rows' => [
                ['GBV prevention programme', 'Sindh Rescue 1122 system', 'World Bank SFERP-II'],
                ['MHM kits distributed', '10,000 kits in 40 schools and communities', 'UNDP Pakistan'],
                ['Livelihoods villages monitored', '382 villages in Gwadar and Lasbela over 37 months', 'IFAD'],
                ['Humanitarian and development monitoring', '40-month TPM in 5 Sindh districts', 'HEKS/EPER'],
                ['Community DRR plans', 'Jacobabad, Kashmore and Shikarpur', 'ACTED'],
                ['Flood resilience M&amp;E', '29-month programme in Dadu, NF and Sanghar', 'Concern Worldwide'],
                ['Social protection feasibility', 'Women agricultural workers in 5 Sindh districts', 'Government of Sindh and World Bank'],
                ['Social safety net evaluation', '7 districts in Sindh and Balochistan', 'Oxfam International'],
            ],
            'contract_value' => 'PKR 320+ million',
            'key_partners' => 'P&amp;D Department Government of Sindh, UNDP, IFAD, HEKS/EPER, Concern Worldwide, ACTED, Oxfam International',
        ],
        'meal' => [
            'tab' => 'MEAL',
            'n' => 8,
            'title' => 'Monitoring, evaluation, learning and impact advisory',
            'intro' => 'Independent, rigorous, utilisation-focused MEAL services enabling institutions to learn continuously, adapt in real time, and demonstrate credible impact.',
            'page' => 'sector-meal.php',
            'impact_rows' => [
                ['Independent evaluations and research', '31+ studies delivered', 'World Bank, UNDP, IFAD, USAID'],
                ['Formative research on social norms', '6 Sindh districts', 'World Bank and SSPA'],
                ['Solar energy project monitoring', '30 districts, 200,000 families', 'World Bank SSEP'],
                ['CATI household survey', '14,000 households in Sindh and Balochistan', 'UNDP 4RF'],
                ['IFAD livelihoods monitoring', '37-month TPM, 382 villages in Gwadar and Lasbela', 'IFAD'],
                ['HEKS/EPER field monitoring', '40-month TPM in 5 Sindh districts', 'HEKS/EPER'],
                ['Flood resilience M&amp;E', '29-month programme in 3 Sindh districts', 'Concern Worldwide'],
                ['Education reform impact assessment', 'Upper Dir and Swat', 'Kindernothilfe Germany'],
                ['UNESCO capacity building evaluation', 'District Education Officers in Balochistan', 'UNESCO Pakistan'],
            ],
            'contract_value' => 'PKR 280+ million',
            'key_partners' => 'UNDP, World Bank, IFAD, HEKS/EPER, Concern Worldwide, Kindernothilfe, UNESCO, Save the Children',
        ],
        'health' => [
            'tab' => 'Health',
            'n' => 9,
            'title' => 'Health systems strengthening and nutrition',
            'intro' => 'Integrated health and nutrition solutions bridging clinical knowledge, community programming, governance reform, and social protection, aligned with SDG 3 and SDG 2.',
            'page' => 'sector-health.php',
            'impact_rows' => [
                ['Formative research on MCH norms', '6 high-burden Sindh districts', 'World Bank and SSPA'],
                ['Multi-sectoral nutrition programme', '13 Sindh districts, design and implementation', 'World Bank and DFID MSAN'],
                ['Stunting and malnutrition WASH', 'Sukkur, NF, Mirpurkhas, Ghotki and Khairpur', 'World Bank'],
                ['Hygiene promotion and BCC', 'Ghotki, Jacobabad and Dadu', 'World Bank and DFID'],
                ['School health and hygiene programmes', '489 schools in Dadu and Naushahro Feroze', 'UNICEF Pakistan'],
                ['MHM education and kit distribution', '10,000 beneficiaries in 40 schools and communities', 'UNDP Pakistan'],
                ['OHS plans developed and implemented', 'Multiple programmes across Sindh', 'World Bank, ADB'],
                ['Community health and safety assessments', 'Multiple donor-funded programmes', 'World Bank, ADB'],
            ],
            'contract_value' => 'PKR 200+ million',
            'key_partners' => 'Sindh Social Protection Authority, LGD Government of Sindh, UNICEF, UNDP, Concern Worldwide, ACTED',
        ],
    ],
];
