<?php
/**
 * Projects portfolio — all fields preserved from legacy projects table.
 * status_key: ongoing | completed (for filters)
 */
return [
    [
        'year' => 'Jan 2024 to April 2024',
        'title' => 'Feasibility Study on Women Agricultural Workers Programme',
        'client' => "Sindh social protection authority\nSocial protection department\nGovernment of Sindh",
        'scope' => '—',
        'area' => "5 District in Sindh\nHala, District Matiari,\nChamber District TandoAllahyar\nNawabShah\nDistrict Shaheed Benazir Abad\nKandiaro\nDistrict NaushahroFeroze\nBakrani District Larkana",
        'status' => 'Ongoing',
        'status_key' => 'ongoing',
    ],
    [
        'year' => 'Jan 2024 to March 2024',
        'title' => 'Socioeconomic Survey of the Selected Old Karachi Areas',
        'client' => 'Project Implementation Unit, Competitive & Livable City of Karachi (CLICK), Local Government Department, Government of Sindh',
        'scope' => '—',
        'area' => 'Old Areas of Karachi',
        'status' => 'Ongoing',
        'status_key' => 'ongoing',
    ],
    [
        'year' => 'Nov 2021 to Dec 2022',
        'title' => 'Design and support consultant for the operations review and performance management of the WASH Program',
        'client' => "Accelerated Action Plan for Nutrition-AAP Project\nImplemented by Local Government Department Government of Sindh (WASH Component)\nFunded by World Bank",
        'scope' => '—',
        'area' => "Project districts 05\nSukkar\nNashoroferoz\nMirpurkhas\nGhotki\nKhairpur",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'July 2022 To December 2022',
        'title' => 'The Study is to identify opportunities for women to engage in CARE International Cash for Work(CFW) programs across Jacobabad Sindh',
        'client' => 'CARE International',
        'scope' => '—',
        'area' => 'Jacobabad Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => "2021-till\nMay\n2022",
        'title' => 'Project Design and Support Consultant (PDSC) for village level disaster resilience solar powered water supply schemes, drainage schemes and School Latrines in priority ODF Certified villages in 05 districts of Sindh',
        'client' => "Local Government Department Government of Sindh Funded by World Bank\nAccelerated action plan(AAP) for reduction of stunting & malnutrition, in Sindh Project",
        'scope' => "The project is planning to provide 400-500 village level disaster resilience solar powered water schemes,125 drainage schemes and latrines in 1000 schools in priority ODF Certified villages in each 05 districts of Sindh for which it is acquiring a firm to coordination with DCCN/ DDMA for identification, selection and designing of above- mentioned sites as per following criteria i.e.\n1. Village must have 150-300 households.\n2. High number of households under poverty line which will be determined by the UCBPRP database.\n3. High rate of incidence of water borne diseases.\n4. No access to safe drinking water\n5. Technically feasible for small scale Water Supply Scheme.",
        'area' => "05 Districts of Sindh\n1- Sukkar\n2- Nashoroferoz\n3- Mirpurkhas\n4- Ghotki\n5- Khairpur",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2020-2021',
        'title' => 'Solar Power Village Level Disaster Resilience Water Supply Scheme and School WASH Design and implementation support, Realtime web-based monitoring, Operation and Maintenance training, and Supervision consultant.',
        'client' => "Local Govt Department Government of Sindh. Funded by World Bank\nSaafSuthro Sindh Program (SSP)",
        'scope' => "Supervision with quality control checks, operation, and maintenance training,CBDRM Training. structure validation, ESMP/EHSH code of conduct implementation as per World Bank Guidelines, billing verification certification, etc. for 400 Village level Solar Powered Water Supply schemes at 13 Districts and 2600 School WASH at 13 Districts 13 of Sindh.\n\nB-Design preparation with BOQ for provision of water either through electric or solar pumping system borehole or any other source as per site requirement, ensuring soil testing, availability of water, yield testing, pre, and post (conducted by contractors) for all 500 small scale water supply schemes. And Pre- and post-water quality testing, and finalized where water quality is as per WHO standers and sufficient water will be accepted available throughout all sessions.\n\nIf water does not meet WHO standers, the consultant will incorporate water treatment methods in the design of water supply schemes. Water Supply Scheme.",
        'area' => "13 districts of Sindh.\nThe number of 400 Solar-powered village-level water supply schemes in 13 Districts of Sindh.\nAnd 2600 School WASH Facilities @ 200 per district in 13 Districts of Sindh.\nCBDRM training for Community and in School\nRealtime web-based Monitoring of operational sites.\nO&M Training ForOperation Maintenance committee for 13 district of Sindh\n.Dadu\n2.Jacobabad\n3.Sanghar.\n4.Tando Mohd Khan.\n5.Tharparkar.\n6.Umerkot.\n7.Thatta.\n8.Sujawal.\n9.Badin.\n10.Kashmore.\n11.Kambar-shahdadkot.\n12.Larkana.\n13.Skikarpur,\nSindh.",
        'status' => 'Realtime web-based monitoring, Operation and Maintenance Training Manual, CBDRM Training Manual, Construction Supervision Manual, Voluntary Land Donation, Design of water supply, and school WASH are completed and approved by the world bank and PIU Karachi.',
        'status_key' => 'completed',
    ],
    [
        'year' => '2019-2020',
        'title' => "Identification and Site Selection of Drinking Water and Sewerage Schemes in 13 Districts of Sindh\nAddendum I: Additional Services of Land Screening, Environment Asst., Water Testing and Voluntary land donation &others for Water Schemes in 13 Districts of Sindh",
        'client' => 'Saaf Suthro Sindh Program (SSP), Local Govt Department Government of Sindh. Funded by World Bank',
        'scope' => "1-Review & analyze secondary data related to the availability of water, its quality & existing water schemes/sources.\n2- Identification of 500-600 existing sewerage schemes in 5200 villages where the project is implemented and subject to rehabilitation\n3- Land Screening, Environmental Screening., Water Testing and Voluntary land donation & others for Water Schemes in 13 Districts of Sindh",
        'area' => "SaafSuthro Sindh Program (SSSP), Local Govt. Department, GOS 13 district of Sindh\n1.Dadu\n2.Jacobabad\n3.Sanghar.\n4.Tando Mohd Khan.\n5.Tharparkar.\n6.Umerkot.\n7.Thatta.\n8.Sujawal.\n9.Badin.\n10.Kashmore.\n11.Kambar-shahdadkot.\n12.Larkana.\n13.Skikarpur,\nSindh.",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2019-2021',
        'title' => 'Project Supervision& Implementation Assistance for Disaster *Climate Resilience Improvement Project in District Umerkot- Sindh',
        'client' => "CARE\nInternational",
        'scope' => "· Identification of deadlines or non-functional water supply & Sewerage schemes according to requirement\n· Hygiene Promotion training\n· Formation of VDC\n· DRR Training\n· Meetings with communities, feasibility reports,\n· Preparation of sharp drawings and BOQ\n· Design of new and Rehabilitation of Pipe line, water distribution System and water storage reservoir and establishment of O&M funds.",
        'area' => "District\nUmerkot–Sindh",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2018-2019',
        'title' => "Ground water resource mapping in district Sanghar,\nUmerkot, and Tharparkar\nSindh",
        'client' => 'UNDP',
        'scope' => "· Meetings with community and farmers, technical evaluation of soil, ground water table, availability of water & water quality\n· To check parameters as per WHO standards, feasibility, and cost estimation for Well Development and Tube well development and establishment of O&M at community-level for sustainability.",
        'area' => "Tharparkar,\nSanghar and\nUmerkot\nDistricts in\nSindh",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2015-2017',
        'title' => "Designing, Site Supervision & Operation and Maintenance Training, Water treatment training and VDC Formation for Construction of 1500 Housing Units with 2 rooms, Verandah, kitchen, latrine & water facility for poor families of 5 districts with development and availability of complete online database of construction sites. (T.Allahyar, Benazirabad, Matiari, Sanghar, Dadu) Sindh'",
        'client' => 'UNDP, Benazir Bhutto housing cell Government of Sindh Karachi',
        'scope' => "Low Cost Housing for Poor people of sindh, Designing, Site Supervision & Operation and Maintenance Training, Water treatment training and VDC Formation for Construction of 1500 Housing Units with 2 rooms, Verandah, kitchen, latrine & water facility for poor families of 5 districts with development and availability of complete online database of construction sites. (T.Allahyar, Benazirabad, Matiari, Sanghar, Dadu) Sindh'",
        'area' => "Benazir Bhutto housing cell Government of Sindh Karachi\nIn 5 Districts TandoAllahyar, Benazirabad, Matiari, Sanghar, Dadu) Sindh'",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2014-2016',
        'title' => "Third-party monitoring of\nConstruction and\nRehabilitation work of Safe\nDrinking-Water schemes with real-time monitoring and evaluation and database management in villages of District Badin and\nMatari.",
        'client' => "Pakistan\nPetroleum\nLimited (PPL)",
        'scope' => "•Identification of dysfunctional and new sites for water supply schemes, NOC from Govt. PHED for schemes, community meetings.\n• To know their drinking water needs.\nTo prepare a feasibility report, technical report, drawing and BOQ preparation, to recommend new/repairing scheme, real-time monitoring and evaluation of ongoing construction work with database management and handover of schemes.",
        'area' => "Pakistan\nPetroleum\nLimited (PPL)\nDistrict Badin and Matari.",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2014- 2016',
        'title' => 'Building Resilience through Community Based Disaster Risk Management – CBDRM in the Sindh Province of Pakistan',
        'client' => 'The United States Agency for International Development (USAID) project represents nearly $1.4 million in disaster risk management assistance from the American people to flood affected people of Pakistan',
        'scope' => "community-based disaster risk management (CBDRM) project, which aims to build the resilience of local communities to resist hazard impact, to bounce back after disasters, and to adapt and change in order to ensure effective recovery. Funded by the United States Agency for International Development (USAID), this project will benefit an estimated 110,879 households in four disaster high risk districts of Sindh, namely Badin, Thatta, Umarkot and Tharparker.\nThis project intends to address the lack of preparation of local communities and the government in dealing with pre- and post-disaster situations. There is an urgent need to develop community based disaster risk management systems in which communities are actively engaged in building their overall resilience to natural disasters. This means putting the people themselves at the heart of decision making and implementation of disaster risk management activities. By supporting the construction and rehabilitation of critical micro-community infrastructures and building the capacity of communities to manage and mitigate resources\nThe Training of Trainers (ToT) under the subject of \"Community Based Disaster Risk Management (CBDRM The objective of the training was to enable project beneficiaries to conduct Disaster Risk Assessment, Develop Risk Management Plans and establish Early Warning Systems through coordination of VDMC/UDMCs with government line departments for timely pre-emption of any hazardous situation\n. For better projection and wider scale dissemination of project objectives the participants who took part in workshops included officials from district government DCO/ADCO/NDMA/DDMA and representatives from the media, Civil Society Organizations, Local Support Organizations (LSOs), Community Organizations (COs) and members.",
        'area' => '3 district of Sindh Badin, Thatta, Umarkot and Tharparker',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2013–2015',
        'title' => 'Sindh Safe Drinking Water and Hygiene Promotion Project (SSDWHPP)',
        'client' => 'USAID',
        'scope' => "Sindh Safe Drinking Water and Hygiene Promotion Project (SSDW-HPP) as part of its goal to improve basic health services for the Pakistani population. The Two-year project (2013–2015) was designed to increase the effectiveness and sustainability of the Clean Drinking Water for all, program by conducting complementary hygiene and sanitation promotion programs, community mobilization initiatives, and diverse capacity-building activities. Specifically, the objective of the project was to improve the health of vulnerable populations and to increase the use of proven interventions to prevent waterborne infectious diseases such as diarrhea.\nSSDW-HPP's geographic scope covered 02 districts of Sindh estimated total population of 12000.\nActivity Description\n· Hygiene promotion and Training. Developing, implementing, and evaluating behavior change communications activities and Trainings to improve safe water management, hand-washing behaviors, and sanitation practices in households. This program included the community hygiene program (including the school program) and the radio program.\n· Capacity building. Strengthening local capacity to manage and operate Water Supply, water treatment plants Sewerage system and HH latrine in a sustainable manner.\n· Technical reviews. Conducting a technical review on water testing methods and household water treatment technologies",
        'area' => 'Two District of Sindh , Umerkot and Badin',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2012-2013',
        'title' => 'Design Supervision and BOQ Preparation for community infrastructure, Shelter, water point, and Latrine etc. and Develop Community mobilization strategy and Training Manual for communities.',
        'client' => 'ACTED Funded Project-Mainstreaming Disaster Risk Reduction (DRR) to enhance community resilience',
        'scope' => "DRR approaches in its relief and recovery interventions, in line with international standards and government priorities. Community organizations are systematically sensitized to disaster risks through the spread of key messages and hazard vulnerability mapping exercises at the start of project implementation. Moreover, all shelter, water point, latrine and community infrastructure schemes rehabilitated or constructed by ACTED are designed to be resilient to specific climatic and disaster threats. Through its 'build it back better' approach, ACTED identifies key techniques and practices that can easily be replicated by target communities using low cost and locally available materials, and provides communities with trainings to ensure that this knowledge is adequately absorbed by beneficiaries for e district of Sindh",
        'area' => "3 District of Sindh\n1- Jacmabad\n2- Kashmore\n3- Shakirpur",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2012-2014',
        'title' => "Construction Monitoring Supervision and SMC Training for\nRehabilitation of Safe\nDrinking Water and Toilet facilities in Govt. Girls\nPrimary Schools in District\nDadu.",
        'client' => 'UNICEF',
        'scope' => "· SMS Training for School WASH Management\n· Construction Supervision\n· Pre and post water quality testing\n· Construction monitoring of latrine,\nSewerage system and Water provision through Deep Handpump",
        'area' => "236 GGPS in\nvillages of\nDistrict\nNoushehro\nFeroze",
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2011-2012',
        'title' => 'Hygiene Promotion in Sindh implementing a two-phase Participatory Hygiene and Sanitation Transformation (PHAST) and Child to Child Methodology in Three Districts of Sidh.',
        'client' => 'ACTED',
        'scope' => "The hygiene promotion component of the project IPECS as implementing partner of ACTED has been implementing a two-phase program using \"Participatory Hygiene and Sanitation Transformation\" (PHAST) and Child-to-Child (CTC) methodology, which provides a framework for the active participation of children in the trainings and for turning the children into active agents of change within their families and communities.\nThe hygiene promotion activities included:\n- Analysis of problems regarding the hygiene facilities and practices\n- Discussion of barriers (to help the children finding ways of blocking the spread of diarrhea)\n- Choosing improved hygiene behaviors\n- Presentation of children to mothers about PHAST\n- Field visits where children and mothers point out good and bad hygiene practices in their own community\n- Hygiene competition with quizzes and debates\n- Street theatre with skits about hygiene practices, games and drama competition.\nThe involvement of mothers and non-school going children has been an important aspect of the hygiene promotion activities.\nThe competitions and theatre have also been a great success, bringing together children, parents and teachers from different schools to share their knowledge about hygiene while having a great time. The theatre group \"Eye View\" has been responsible for hosting the street theatre together with ACTED hygiene promoters.\nA Knowledge, Attitude and Practices (KAP) survey was conducted at the start of the program to determine the quality of the hygiene practices and identify specific needs in terms of hygiene education. The survey will be repeated at the end of the program to assess the impact of the hygiene promotion activities on the knowledge and practices of the beneficiaries.",
        'area' => '3 District of Sindh .Gotki , Jacamabad and Dadu',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
];
