<?php
/**
 * Projects portfolio - all fields preserved from legacy projects table.
 * status_key: ongoing | completed (for filters)
 */
return [
    [
        'year' => 'Oct 2025 to Mar 2027 (18 months)',
        'title' => 'Consultancy Services for Community Engagement to Prevent and Mitigate GBV under SFERP Phase-II',
        'client' => "Planning & Development Department, Government of Sindh (SFERP-II)\nFunded by World Bank",
        'scope' => "Assessment & Planning: Conducted baseline assessments of GBV/SEA/SH risks, prevention and response capacity, and comprehensive service mapping across 12 districts.\nBCC and Communication Strategy: Developed Behaviour Change Communication (BCC) and Communication Strategies for Sindh Emergency Rescue 1122 teams across 5 districts, covering multi-channel communication planning and campaign design.\nDRR and Early Warning Training: Delivered 17 early warning and emergency response training sessions attended by 290 Rescue 1122 team members across 5 districts; developed DRR Response Plan and DRR Policy for Sindh Emergency 1122 teams.\nCapacity Building (ToT): Delivered Training of Trainers (ToT), structured coaching, and institutional capacity-building sessions for Rescue 1122 management, district staff, and field teams on prevention, safe disclosure handling, confidentiality, and survivor-centred response.\nGrievance Redressal Mechanism (GRM): Designed and operationalised confidential, survivor-centred complaint intake and handling systems with multiple safe channels, escalation and closure protocols, referral pathways, and secure recordkeeping.\nReferral Pathways: Developed multi-sector survivor referral pathways linking legal, psychosocial, health, and protection services with safe, ethical case management coordination.\nInstitutional Instruments: Developed comprehensive policies, SOPs, and Codes of Conduct addressing SEA/SH controls, reporting obligations, and enforcement mechanisms.\nCommunity Engagement & BCC: Implemented awareness and behaviour change communication campaigns promoting zero tolerance and safe reporting mechanisms across 10 districts, engaging students, teachers, SMC members, and communities.\nBeneficiaries Trained: 2,998 participants trained to date, including 952 students, teachers, SMC members, and community members; 47 PIU team members; and 1,999 Rescue 1122 officials and field staff, including 490 women.\nMEAL/Reporting: Established MEAL framework aligned with project results; conducted pre/post assessments; delivered periodic reporting (monthly/quarterly/annual) with gender-disaggregated data and corrective action follow-up.",
        'area' => 'Sindh Province, Pakistan (Rescue 1122 Coverage)',
        'status' => 'Ongoing',
        'status_key' => 'ongoing',
    ],
    [
        'year' => 'Oct 2025 to Mar 2026 (6 months)',
        'title' => 'Community Mobilisation and Awareness Sessions on Menstrual Hygiene Management (MHM) and Delivery of Menstrual Health Kits',
        'client' => "UNDP Islamabad, Pakistan\nFunded by UNDP Pakistan",
        'scope' => "Planning & Coordination: Developed detailed district-wise activity plans and coordinated with UNDP, Education, and Health Departments; established school and community scheduling to avoid disruption to academic calendars.\nBeneficiary Mapping: Conducted baseline profiling and beneficiary mapping for approximately 10,000 participants to support targeted planning and effective implementation.\nToT Delivery: Delivered structured Training of Trainers (ToT) for facilitators using Government of Sindh-approved MHM modules, ensuring standardised, quality-assured, and culturally appropriate delivery.\nMHM Awareness Sessions: Successfully delivered 176 in-person awareness sessions and workshops across 46 schools and 58 villages/communities using participatory and gender-sensitive facilitation approaches in Sindhi language, addressing menstrual hygiene management, health awareness, dignity, confidence building, and socio-cultural barriers.\nIEC Material Development: Developed, printed, and distributed Sindhi-language IEC materials including flyers, handbooks, and informational pamphlets to reinforce key learning messages.\nKit Distribution: Procured, stored, transported, and distributed approximately 10,000 UNDP-approved menstrual health kits with beneficiary verification, signed acknowledgements, and transparent delivery documentation.\nWaste Management: Designed and implemented safe menstrual waste management systems; installed covered bins and waste collection units.\nStigma Reduction: Engaged parents, teachers, and local leaders to reduce stigma and school absenteeism related to menstruation.\nGovernance: Formed and strengthened School and Community WASH Committees for oversight and sustainability.\nPre/Post Assessment & Safeguarding: Conducted pre/post assessments to measure knowledge change; collected feedback forms from all participants; maintained full compliance with UNDP safeguarding standards including informed consent, confidentiality, and Do-No-Harm principles.",
        'area' => '46 Schools and 58 Communities, Sindh (approximately 10,000 beneficiaries)',
        'status' => 'Ongoing',
        'status_key' => 'ongoing',
    ],
    [
        'year' => 'Oct 2025 to Mar 2026 (5 months)',
        'title' => "Citizens' Perception and Performance Monitoring Survey (4RF - Flood Recovery)",
        'client' => 'UNDP Pakistan',
        'scope' => "Survey Design: Developed methodology and representative sampling framework; established survey protocols and quality assurance standards.\nTools & Languages: Developed questionnaires and translated/adapted them into English, Urdu, Sindhi, and Balochi with consistency and skip-logic checks.\nPilot & Refinement: Conducted baseline review, pilot testing, and tool finalisation to ensure validity and reliability.\nHR & Training: Recruited and trained enumerators, including female data collectors, on research ethics, respondent safety, and quality control procedures.\nCATI Execution: Conducted computer-assisted telephonic interviews (CATI) with real-time supervision, call monitoring, back-checks, and data validation across 14,000 households.\nData Analysis: Performed data cleaning and analysis in SPSS/Stata with gender and vulnerability disaggregation.\nOutputs: Produced analytical reports, dashboards, and policy briefs with actionable recommendations for adaptive recovery planning.\nFeedback Loop: Integrated community engagement and feedback to support accountability and adaptive programme management.",
        'area' => 'Sindh & Balochistan (Telephonic CATI; 14,000 Households)',
        'status' => 'Ongoing',
        'status_key' => 'ongoing',
    ],
    [
        'year' => 'Feb 2025 to Jan 2026 (12 months)',
        'title' => 'Community Awareness and Project Implementation Support Consultant - Sindh Solar Energy Project (SSEP)',
        'client' => "Sindh Solar Energy Project (Energy Department, Government of Sindh)\nFunded by World Bank (Project ID: P159712)",
        'scope' => "IEC/BCC Material Development: Developed and disseminated IEC/BCC materials including brochures, posters, and digital content in Sindhi and Urdu, ensuring accessibility, cultural relevance, and effective community outreach.\nDistrict-Level Awareness Events: Organised 147 district-level awareness events across 17 Sindh districts, each attended by a minimum of 700 participants including elected representatives, Deputy Commissioners, and Education Department heads; total beneficiaries reached: 200,000 households; full event logistics managed by IPECS including seating, catering, campaign materials, and IEC distribution.\nDigital Dissemination: Managed all programme social media platforms; disseminated 2.3 million WhatsApp awareness messages and SMS alerts to listed beneficiaries.\nRobocall Campaign: Delivered 600,000 robocalls providing three awareness calls per beneficiary across the programme area.\nCall Centre & GRM Operations: Managed a dedicated call centre with a toll-free number for beneficiary feedback; developed a digital data management system and dashboard to record all calls, SMS messages, and awareness sessions.\nGRM Design & Complaint Tracking: Designed, operationalised, and managed the GRM with complaint tracking, resolution documentation, escalation protocols, and monthly reporting.\nIndependent Monitoring: Conducted field verification of solar home system (SHS) installations and service delivery against technical specifications and rollout plans.\nSafeguards/ESF: Verified compliance with World Bank Environmental and Social Framework (ESS1-ESS10), including labour standards, SEA/SH risk controls, and community health and safety.\nESMP & OHS: Reviewed and verified contractor ESMPs, OHS plans, incident reporting, and corrective actions.\nStaff Training: Trained project staff and support teams on consumer engagement, complaint handling, communication standards, and service delivery protocols.\nM&E & Reporting: Developed monitoring dashboards; produced monthly content plans, progress reports, success stories, and beneficiary feedback documentation for adaptive management and donor compliance.",
        'area' => '30 Districts, Sindh (approximately 200,000 families)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Dec 2024 to May 2025 (6 months)',
        'title' => 'Formative Research on Norms and Behaviours Affecting Maternal and Child Health (MNCH)',
        'client' => "Sindh Social Protection Authority (SSPA), Government of Sindh\nFunded by World Bank (Project ID: P178532)",
        'scope' => "Research Design: Developed mixed-methods framework (quantitative and qualitative), sampling strategy, and implementation plan.\nTools Development: Created questionnaires, FGD guides, and KII templates with gender and cultural sensitivity and ethical safeguards.\nKAP Assessment & Social Norms Analysis: Conducted in-depth assessment of barriers affecting uptake of key MNCH services including antenatal care, institutional delivery, postnatal care, birth registration, exclusive breastfeeding, complementary feeding, and immunisation, examining local beliefs, traditions, and practices shaping health-related decision-making.\nCommunication Channel Mapping: Analysed existing communication channels and information pathways including family and community networks, health workers, mobile and digital platforms, WhatsApp, SMS, community gatherings, religious spaces, and traditional media to determine the most effective routes for message dissemination and behaviour change.\nWASH-MCH Linkages: Assessed water, hygiene, and sanitation-related knowledge, attitudes, and practices in relation to maternal and child wellbeing.\nMamta-CCT Programme Assessment: Assessed beneficiary knowledge and utilisation of the Mamta-CCT programme and other locally used platforms, identifying awareness gaps and access barriers.\nFieldwork: Recruited and trained enumerators; managed multi-district logistics and supervision; conducted household surveys, FGDs, and KIIs with consent, confidentiality protocols, and quality assurance checks.\nAnalysis: Conducted quantitative analysis (SPSS) and qualitative analysis (NVivo) to identify behavioural drivers, barriers, and opportunities.\nDeliverables: Produced comprehensive research report with actionable BCC programming recommendations for World Bank and Government of Sindh.\nCompliance: Ensured ESF (ESS4/ESS10) and ethical research compliance throughout.",
        'area' => '6 Districts, Sindh (Sujawal, Tharparkar, Tando Allahyar, Sanghar, Ghotki, Kambar Shahdadkot)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Mar 2024 to Jun 2025 (15 months)',
        'title' => 'Project Supervision and Implementation Support Services - Sindh Coastal Resilience Integrated Programme (SCRIP)',
        'client' => "Aga Khan Rural Support Programme (AKRSP) Sindh\nFunded by Embassy of Denmark / Danish Ministry of Foreign Affairs",
        'scope' => "CBDRM Training & Community Awareness: Organised 23 CBDRM training events and delivered 211 community awareness and campaign sessions across Thatta and Sujawal districts.\nCommunity Structure Formation: Formed 157 DRR Committees across 157 villages; established 32 WASH Committees and 51 School WASH Clubs across 51 schools.\nSchool-Level DRR & WASH Awareness: Delivered DRR and WASH awareness programming across 51 schools, covering disaster preparedness and education continuity.\nRobocall & SMS Campaign: Delivered robocall awareness campaign covering 145,000 households across 3 districts; disseminated 213,000+ SMS messages in local language to beneficiaries.\nIEC & BCC Material Development: Developed local-language BCC and IEC materials in Sindhi for CBDRM and WASH awareness targeting low-literacy rural audiences.\nToll-Free Feedback System: Operated a toll-free beneficiary feedback system for community complaint and feedback collection.\nWASH Infrastructure Supervision: Supervised installation of solar reverse osmosis (RO) plants for clean drinking water and safe water and sanitation schemes across coastal communities.",
        'area' => 'Thatta and Sujawal Districts, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Jan 2024 to Mar 2024 (3 months)',
        'title' => 'Socioeconomic Survey of Selected Old Karachi Areas',
        'client' => "Competitive & Livable City of Karachi (CLICK), Local Government Department, Government of Sindh\nFunded by World Bank",
        'scope' => "Desk Review: Compiled and analysed secondary data to inform survey design and methodology.\nSurvey & Mapping: Conducted household and settlement-level surveys with mapping updates.\nSampling: Applied scientifically justified sampling methodology (4% in larger areas to 100% in smaller settlements).\nData Capture: Collected data on demographics, income and expenditure, economic activities, employment, utilities, and service access.\nInfrastructure Assessment: Assessed water supply, sanitation, solid waste management (SWM), parks, markets, roads, and street lighting conditions.\nInclusion: Ensured gender-disaggregated data collection and inclusion of persons with disabilities.\nDigital Quality Control: Utilised tablet and mobile-based data collection with spot checks and validation protocols.\nReporting: Delivered comprehensive socioeconomic profiling analysis to support planning and investment prioritisation.",
        'area' => 'Old City Areas, Karachi, Pakistan',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Jan 2024 to Jun 2024 (6 months)',
        'title' => 'Feasibility Study on Women Agricultural Workers Programme',
        'client' => "Sindh Social Protection Authority (SSPA), Social Protection Department, Government of Sindh\nFunded by Government of Sindh",
        'scope' => "Diagnostic Assessment: Assessed vulnerabilities and protection challenges faced by women agricultural workers, including income insecurity, discrimination, and access constraints.\nSystems Review: Evaluated beneficiary identification and registration processes, including linkages with Labour Department systems.\nHealth Access: Reviewed healthcare infrastructure and access with emphasis on maternal and child health outcomes.\nCCT Design: Designed a conditional cash transfer (CCT) framework including eligibility criteria, benefit size, conditionalities, payment frequency, and payment channels.\nImpact & Economics: Analysed expected programme impacts (poverty reduction, health outcomes, women's empowerment) and conducted cost-benefit analysis, fiscal implications assessment, and return on investment (ROI) analysis.\nImplementation Strategy: Developed institutional arrangements, roles and responsibilities, and phased rollout plan.\nM&E Framework: Established key performance indicators (KPIs), monitoring plan, and data collection methods.\nPolicy Recommendations: Provided evidence-based recommendations for the Government of Sindh.",
        'area' => '5 Districts, Sindh (Hala-Matiari; Chambar-Tando Allahyar; Nawabshah-Shaheed Benazirabad; Kandiaro-Naushahro Feroze; Bakrani-Larkana)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Nov 2023 to Jun 2024 (8 months)',
        'title' => 'Installation, Operations and Monitoring of Piezometers in Sindh',
        'client' => "Food and Agriculture Organization (FAO)\nFunded by Green Climate Fund (GCF)",
        'scope' => "Engineering Works: Completed drilling and construction of 10 new boreholes (5 per district) with piezometer installation for groundwater monitoring.\nSafeguards Planning: Developed and implemented a Site-Specific Environmental and Social Management Plan (SSEMP).\nCompliance: Ensured alignment with GCF/FAO and national environmental and social standards.\nRisk Management: Identified environmental and community risks; implemented prevention and mitigation measures.\nMonitoring: Conducted on-site environmental and social compliance monitoring throughout project execution; documented findings and corrective actions.",
        'area' => 'Sanghar & Umerkot, Sindh (10 Boreholes)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Sep 2023 to Jan 2024 (4 months)',
        'title' => 'Strategic Transaction and Procurement Readiness Support for Social Development Outcomes',
        'client' => "Research and Development Foundation (RDF)\nFunded by RDF",
        'scope' => "Inception: Conducted inception workshop; refined work plan and methodology; reviewed documentation and stakeholder expectations.\nTransaction Structuring: Assessed partnership modalities (PPP and concession variants) and recommended the optimal model; documented institutional requirements.\nProcurement Strategy: Developed competitive bidding structure, eligibility criteria, and procurement procedures.\nEvaluation Framework: Designed technical and financial scoring and weighting systems, pass/fail thresholds, and a transparent evaluation process ensuring value for money (VFM).\nRFP Package: Prepared complete Request for Proposals (RFP) and bid documents including instructions, forms, templates, technical/financial/compliance requirements, and evaluation tools.\nDraft Agreement: Drafted concession/partnership agreement covering scope, roles, term, pricing/payment or revenue share, performance standards, service levels, termination, dispute resolution, compliance, and governing law.\nKPIs: Developed a KPI set and performance monitoring framework for the contract lifecycle.\nRisk Allocation: Conducted risk assessment covering construction, commercial, financial, regulatory, demand, and operational risks with allocation matrix and mitigation measures.\nFinancial Structuring: Developed cost and revenue assumptions, projections, viability analysis, and sensitivity analyses.\nConsultations: Facilitated stakeholder consultations and integrated feedback.\nFinal Package: Delivered consolidated procurement-ready package for issuance.",
        'area' => 'Thatta, Tando Mohammad Khan, Sujawal, Umerkot, Mirpurkhas, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Nov 2022 to Jun 2023 (9 months)',
        'title' => 'Consultancy Assignment for Teacher Training and Educational Development in Coastal Area Schools',
        'client' => 'Education and Literacy Department, Government of Sindh',
        'scope' => "Training Needs Assessment: Conducted Training Needs Assessment (TNA) and baseline studies to identify gaps in teaching practices, WASH awareness, student behaviour, and institutional capacity; prepared detailed training plans, implementation methodologies, and district-wise work schedules.\nTeacher Training: Trained 380 teachers including 117 female teachers across 160 target schools using child-centred pedagogy, WASH-in-Schools (WinS), hygiene education, and Behaviour Change Communication (BCC) modules.\nToT & On-Site Mentoring: Delivered Training of Trainers (ToT), coaching, and on-site mentoring to strengthen teacher capacity and support sustained application of learning at school level.\nIEC Material Development & Distribution: Developed and distributed WASH-related IEC materials across 160 schools.\nGender-Sensitive Facilitation: Applied gender-sensitive, inclusive, and child protection-oriented facilitation approaches throughout, with close coordination with district education authorities, school management, and local stakeholders.\nM&E & Reporting: Established and implemented monitoring and evaluation systems including pre/post assessments, classroom observations, and behavioural outcome tracking; prepared progress and completion reports documenting achievements, field findings, and recommendations.",
        'area' => 'Thatta, Badin, and Tando Muhammad Khan, Sindh (160 Schools)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Mar 2022 to Jun 2023 (16 months)',
        'title' => 'Development of PPP Bidding Package for Secondary Education Department (SED), Government of Balochistan',
        'client' => "Secondary Education Department, Government of Balochistan\nFunded by Global Partnership for Education (GPE), administered by World Bank; European Commission (Additional Financing)",
        'scope' => "Component 1 - Access & Equity: Supported community school mechanisms and student transition interventions; advised on equity and gender-responsive approaches; facilitated community engagement, consultations, and GRM; tracked enrolment, retention, and dropout trends with a focus on girls' education.\nComponent 2 - Quality & Accountability: Supported teacher training and early childhood education (ECE) rollout; reviewed and adapted teaching and learning materials; monitored classroom practices and implementation fidelity; strengthened school-level data collection, validation, reporting, and data use for planning and budgeting.\nComponent 3 - Results & Advisory: Supported results-based monitoring frameworks; tracked PDO and intermediate indicators; produced World Bank-compliant progress reports, results updates, and analytical briefs; supported supervision missions and documentation.\nComponent 4 - Transition & Institutional Strengthening: Provided advisory on sustainability and institutional transition; delivered capacity building for SED and district staff; produced completion, transition, and knowledge products; coordinated with World Bank, UNICEF, European Commission, and other stakeholders.",
        'area' => 'Quetta (Balochistan); Jacobabad, Khairpur, Sukkur (Sindh); Target: 123 Schools (Girls-Focused)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Nov 2021 to Dec 2023 (26 months)',
        'title' => 'Project Implementation Support Consultant for Water Supply, Sanitation and Hygiene (WASH) - Accelerated Action Plan for Nutrition (AAP)',
        'client' => "Local Government Department, Government of Sindh (WASH Component)\nFunded by World Bank (Project ID: P161624) - Sindh Response to Stunting, Accelerated Action Plan for Nutrition (AAP)",
        'scope' => "BCC Strategy & Participatory Methodologies: Developed and implemented Behaviour Change Communication (BCC) strategies using participatory methodologies including CHAST (Children's Hygiene and Sanitation Training) and FAST, adapted to local socio-cultural contexts; conducted school-based hygiene education sessions through Children's Clubs and community platforms.\nIEC Material Development: Designed, produced, and distributed IEC materials for schools, households, and communities to reinforce key health, hygiene, and behaviour change messages.\nToT & Cascade Training: Delivered Training of Trainers (ToT) and structured capacity-building activities for teachers, CBO leaders, health workers, women, youth, and community volunteers; developed local \"Ambassadors of Change\" to support community outreach.\nCommunity Structure Formation: Facilitated formation and support of Village Organisations (VOs), Community-Based Organisations (CBOs), Community Development Plans, ODF-related initiatives, O&M Committees, and School WASH Club Committees with strong women's participation.\nMHM Awareness: Conducted targeted MHM awareness sessions for adolescent girls using gender-sensitive engagement approaches promoting dignity, privacy, and safe participation.\nEngineering/Design: Developed designs for village water supply, sanitation/sewerage, solid waste management (SWM), and school WASH interventions including solar-powered systems.\nSupervision/QA: Monitored construction, ensured quality assurance, and provided technical troubleshooting.\nInstitutional Setup: Established District Coordination Committees (DCCs), Village WASH Committees (VWCs), and Village Development Committees (VDCs) for coordination and governance.\nGender & Safeguards: Implemented Gender Action Plan aligned with World Bank safeguards; established Grievance Redressal Mechanism (GRM).\nKAP Surveys & M&E: Conducted KAP surveys, spot checks, and beneficiary feedback collection; ensured compliance with World Bank ESF requirements throughout implementation.",
        'area' => '5 Districts of Sindh (Sukkur, Naushahro Feroze, Mirpurkhas, Ghotki, Khairpur)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2021 to 2023 (3 months bid/design + 18 months construction supervision)',
        'title' => 'Development Project Including EPC Procurement Support and Construction Phase Oversight',
        'client' => "Save the Children\nFunded by Save the Children / Federal Ministry of Education, Pakistan",
        'scope' => "Mobilisation: Developed work plan, staffing structure, reporting lines, site access protocols, and security procedures.\nDue Diligence: Conducted site verification and technical assessments including measurements and risk/constraint identification.\nBid/Design Support: Reviewed and validated designs; developed technical specifications, Bills of Quantities (BOQs), cost estimates, tender documents, and procurement packages.\nEPC Procurement Support: Facilitated pre-bid meetings, clarifications, bid evaluation support, and award documentation in accordance with applicable procurement rules.\nConstruction Supervision: Provided field supervision and QA/QC inspections; verified workmanship and materials; supported measurement and certification for interim payment certificates (IPCs); verified progress against milestones.\nContract Administration: Reviewed contractor submissions including work programmes, method statements, shop drawings, and material approvals; supported variation and claim management; maintained change control tracking.\nE&S/HSE: Monitored compliance with environmental and social safeguards, labour standards, and occupational health and safety (OHS); implemented SEA/SH mitigation and incident escalation protocols.\nStakeholder Coordination: Coordinated with communities and provided grievance-handling inputs during construction.\nCompletion/Handover: Supported snagging and defect rectification; facilitated testing and commissioning; prepared handover documentation; verified as-built records.\nReporting: Delivered periodic and final reports and dashboards with supporting evidence including photographs, registers, non-conformance reports, and corrective actions.",
        'area' => 'Quetta (Balochistan); Jacobabad, Khairpur, Sukkur (Sindh); Target: 123 Schools',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Jun 2020 to Dec 2021 (18 months)',
        'title' => 'Community Engagement and Implementation Support Consultant - Multi-Sectoral Action for Nutrition (MSAN) / Saaf Suthro Sindh Programme',
        'client' => "Local Government Department & Agriculture Department, Government of Sindh\nFunded by World Bank & DFID (Project ID: P158769)",
        'scope' => "Detailed Engineering: Prepared designs, drawings, and BOQs for 650 water supply schemes, 400 drainage/sewerage schemes, and 2,600 school WASH interventions.\nSWM Systems: Designed solid waste management systems including collection, segregation, composting, and safe disposal mechanisms with operational guidance.\nTechnical Investigations: Conducted soil testing, groundwater yield assessments, and pre/post water quality testing.\nSupervision/Compliance: Provided continuous construction supervision and quality monitoring ensuring World Bank ESMF compliance.\nHygiene Promotion & BCC: Delivered hygiene promotion and awareness interventions at community and school levels with a strong focus on improving health knowledge and promoting positive behaviour change.\nMHM Training: Conducted targeted MHM awareness and training activities for adolescent girls, women, and schoolgirls, ensuring dignity, privacy, and gender-sensitive facilitation.\nSchool WASH Clubs & Community Structures: Established School Children's Clubs and \"Ambassadors of Change\" programmes; established male and female WASH committees with strong women's participation; formed local coordination groups.\nMosque-Based Community Messaging: Coordinated mosque-based messaging for WASH and hygiene promotion.\nCLTS & ODF Certification: Implemented Community-Led Total Sanitation (CLTS) processes and supported progress toward Open Defecation Free (ODF) certification.\nCommunity Institutions: Formed and trained Village Development Committees (VDCs), WASH Committees, O&M Committees, and GRM Committees.\nCapacity Building: Delivered training on O&M, hygiene promotion, behaviour change communication (BCC), and disaster risk reduction (DRR).\nBaseline & KAP Surveys: Conducted damage and needs assessments, socio-economic baseline studies, and KAP surveys to inform planning.\nGRM & Beneficiary Feedback: Established and operationalised beneficiary feedback mechanisms and field monitoring systems ensuring adherence to World Bank safeguard requirements.",
        'area' => '13 Districts, Sindh; Coverage: 1,300 Villages and 380 Schools',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Jun 2020 to Oct 2020 (4 months) + Addendum',
        'title' => 'Need Assessment, Identification and Site Selection of Drinking Water and Sewerage Schemes - Saaf Suthro Sindh Programme (SSSP)',
        'client' => "Saaf Suthro Sindh Programme (SSSP), Local Government Department, Government of Sindh\nFunded by World Bank",
        'scope' => "Situation Review: Analysed secondary data on water availability, quality, and existing schemes.\nScheme Identification: Identified 500-600 existing sewerage schemes for rehabilitation across 5,200 villages.\nScreening/Safeguards: Conducted land screening, environmental screening, water testing, and voluntary land donation documentation; prepared Environmental and Social Management Plans (ESMPs) through community consultations.\nCommunity Organisation: Formed Village Organisations (VOs), Grievance Redressal Committees (GRCs), and O&M Committees; established Water Committees and Memoranda of Understanding (MOUs).\nCapacity Building: Delivered training on O&M, masonry skills, District Coordination Committee for Nutrition (DCCN), water quality, and treatment.\nHygiene/DRR: Conducted hygiene promotion training for women and children; delivered disaster risk reduction (DRR) training.\nAddendum: Provided extended due diligence and safeguard services as required.",
        'area' => '13 Districts, Sindh; Coverage: 5,200 Villages',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Mar 2017 to Feb 2019 (22 months)',
        'title' => 'Project Operations and Management Consultant - Sustainable Land Management Programme (SLMP-II)',
        'client' => "UNDP Pakistan\nImplementing Partners: Ministry of Climate Change (Pakistan) and P&DD, Government of Sindh",
        'scope' => "Community Organisation: Facilitated formation of community organisations and farmer groups; conducted capacity building for community members and local institutions on sustainable land management practices and water for agriculture.\nPolicy Mainstreaming: Refocused integrated land-use policies and mainstreamed Sustainable Land Management (SLM) into sectoral policies.\nCapacity Building: Institutionalised SLM capacity building for professionals and government officials.\nPlanning Tools: Developed district and village land-use plans and operationalisation tools; established and followed up on Decision Support System.\nManagement Strengthening: Validated and adjusted results framework; strengthened management arrangements and coordination mechanisms.\nMonitoring/Reporting: Enhanced monitoring and reporting systems, risk management, and financial procedures.\nCommunication/Knowledge: Developed communication strategy and knowledge management system; updated stakeholder engagement plan.\nGovernance/Inclusion: Institutionalised governance mechanisms for sustainability; mainstreamed gender and social equity; aligned guidance with the Plant4Pakistan initiative.",
        'area' => 'Umerkot, Tharparkar, Sanghar, Jamshoro, Badin, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2017 to 2018 (12 months)',
        'title' => 'Impact Assessment of Education Reforms: Education Sector Development - Addressing School Factors Affecting Access to Quality Education',
        'client' => 'Kindernothilfe (KNH)',
        'scope' => "Research Design/Fieldwork: Assessed factors affecting equity of access and quality across pre-primary to senior secondary education levels.\nAnalysis: Evaluated teaching-learning environment, curriculum implementation, classroom practices, and distribution of financial, human, and physical resources.\nTraining Materials: Developed evidence-based training curriculum and materials.\nCapacity Building: Managed participant selection and delivered training for education stakeholders; strengthened research and evidence-use capacity.",
        'area' => 'Upper Dir & Swat, Khyber Pakhtunkhwa',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Mar 2016 to Nov 2016 (9 months)',
        'title' => 'Transaction Structuring and Risk Analysis for Performance-Based Social Safety Net Targeting Services',
        'client' => 'Oxfam International',
        'scope' => "Surveys/Qualitative Learning: Conducted baseline and endline quantitative surveys complemented by FGDs and in-depth interviews (IDIs) capturing beneficiary experiences and system gaps.\nM&E: Implemented ongoing monitoring with stakeholder consultations and feedback integration for adaptive management.\nTargeting Errors: Identified inclusion and exclusion errors through interviews with excluded households and local stakeholders; provided error profiling insights.\nBest Practices: Reviewed NGO/INGO targeting and delivery approaches; documented lessons and recommendations.\nOperations Review: Conducted process evaluation and developed system improvement recommendations; created clear visualisation outputs for decision-makers.\nRisk/Performance Focus: Analysed risk considerations including data integrity, governance, and operational risks; provided performance-oriented recommendations to improve service delivery effectiveness.",
        'area' => '7 Districts, Sindh & Balochistan',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2016 to 2018 (24 months)',
        'title' => 'Impact Assessment of SIDA CSO Framework - Community Mobilisation and Awareness',
        'client' => "Save the Children Pakistan\nFunded by SIDA (Swedish International Development Cooperation Agency)",
        'scope' => "Studies: Conducted pre-KAP survey, curriculum review, positive discipline manual development, and child rights situation analysis.\nConsultations: Facilitated stakeholder consultations and validation sessions.\nAdvocacy/Media: Implemented campaign against corporal punishment using radio and cable TV messaging.\nTeacher Training: Delivered orientation and training for 1,200 teachers on positive disciplining techniques.\nSchool Governance: Formed Parents-Teachers Committees; trained School Management Committees (SMCs); developed school implementation plans; assessed school facilities.\nCommunity Mobilisation: Conducted enrolment drives and gender sensitisation consultations to promote girls' education at district level.",
        'area' => 'Kashmore, Jacobabad, Jamshoro, Umerkot, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Feb 2015 to Mar 2018 (37 months)',
        'title' => 'Third-Party Monitoring, Operational Review, and Support Consultant - Gwadar-Lasbela Livelihoods Support Project',
        'client' => "International Fund for Agricultural Development (IFAD)\nFunded by IFAD",
        'scope' => "Third-Party Monitoring (TPM): Conducted regular field verification of interventions in community development, fisheries development, and rural infrastructure.\nOperational Reviews: Assessed effectiveness and efficiency; identified implementation bottlenecks and recommended corrective measures.\nMonitoring Systems: Developed monitoring plans covering activities, timelines, and methods; conducted routine spot checks.\nDocumentation: Reviewed project documents and reporting for accuracy and timeliness.\nCapacity Support: Provided technical assistance and capacity-building support to staff and beneficiaries.\nReporting: Delivered comprehensive reports with findings, recommendations, and best practices.",
        'area' => 'Gwadar & Lasbela, Balochistan (382 Villages)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2015 to 2017 (24 months)',
        'title' => 'Evaluation of UNESCO Project: Capacity Building of District Education Officers in Educational Planning, Implementation and Community Participation',
        'client' => "UNESCO Pakistan & AEPAM (Ministry of Education)\nFunded by UNESCO Pakistan",
        'scope' => "Evaluation Design: Developed evaluation approach and tools aligned with project objectives and district governance context.\nData Collection: Administered structured questionnaires and collected inputs from Executive District Officers (EDOs), District Education Officers (DEOs), Deputy DEOs, Assistant Education Officers (AEOs), and school heads.\nAssessment: Evaluated decentralised planning, implementation practices, and community participation mechanisms.\nGap Analysis: Identified capacity gaps and implementation constraints.\nRecommendations: Provided evidence-based recommendations to strengthen education planning, implementation, and local governance.",
        'area' => 'Balochistan',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'May 2014 to Jan 2015 (9 months)',
        'title' => 'Feasibility Study for Socio-Economic and Institutional Reforms in Katchi Abadis',
        'client' => "Sindh Cities Improvement Programme (SCIP), Local Government Department, Government of Sindh\nFunded by Asian Development Bank (ADB)",
        'scope' => "Comprehensive Assessment: Assessed housing, WASH, health, education, and socio-economic conditions in informal settlements.\nStakeholder Identification: Identified and engaged stakeholders including residents, local authorities, and relevant organisations.\nSocio-Economic Analysis: Analysed income, employment, and service access using surveys, interviews, FGDs, and literature review.\nInstitutional Review: Reviewed policies, regulations, and governance arrangements.\nFeasibility/Options: Assessed feasibility of reforms; prioritised and identified practical reform pathways.\nRecommendations: Provided evidence-based recommendations for policy reforms, infrastructure investment, and community participation mechanisms.",
        'area' => 'Sukkur, Sindh (17 Main Katchi Abadis)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Mar 2014 to Dec 2014 (10 months)',
        'title' => 'Third-Party Monitoring of Construction and Rehabilitation of Safe Drinking Water Schemes',
        'client' => "Pakistan Petroleum Limited (PPL) - CSR Programme\nFunded by Pakistan Petroleum Limited (PPL)",
        'scope' => "Site Identification: Identified dysfunctional and new sites; conducted community needs meetings.\nRegulatory Coordination: Obtained Public Health Engineering Department (PHED) No Objection Certificates (NOCs); ensured compliance with procedures.\nTechnical Documentation: Prepared feasibility and technical reports, drawings, and Bills of Quantities (BOQs).\nConstruction Monitoring: Conducted real-time monitoring of construction quality and progress; maintained database and evidence tracking.\nOperational Reviews: Performed spot checks and process evaluations on a monthly/quarterly basis.\nBCC/GRM Review: Assessed social mobilisation, behaviour change communication (BCC) delivery, and GRM effectiveness.\nFeedback & Surveys: Collected beneficiary feedback and conducted KAP surveys.\nKPIs & Handover: Monitored key performance indicators (KPIs) and facilitated formal handover of completed schemes.",
        'area' => 'Badin & Matiari, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Jan 2014 to Apr 2017 (40 months)',
        'title' => 'Third-Party Field Monitoring of Humanitarian and Development Interventions',
        'client' => "HEKS/EPER (Swiss Church Aid)\nFunded by HEKS/EPER",
        'scope' => "Tools Development: Developed and refined monitoring instruments for implementing partners.\nTeam Mobilisation: Mobilised and trained five monitoring teams comprising 20 monitors.\nField Monitoring: Conducted observations, verification, and information collection across WASH, Education, Health, and Child Protection & Inclusion (CPI) activities.\nReporting: Provided daily updates to hubs; delivered monthly monitoring reports highlighting progress, gaps, and success stories.\nOperations Review: Conducted spot checks and process evaluations.\nKAP & Performance: Administered KAP surveys; measured performance against M&E indicators.\nBeneficiary Feedback: Collected and analysed structured feedback to inform programme improvements.",
        'area' => '5 Districts, Sindh (Education, WASH, Child Protection & Inclusion)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Nov 2013 to Apr 2015 (18 months)',
        'title' => 'Community Mobilisation Strategy, Training Manual, and Operation Plans for Flood-Affected Communities (DRR)',
        'client' => 'ACTED',
        'scope' => "Strategy Development: Developed community mobilisation strategy for flood-affected settings.\nTraining Package: Created disaster risk reduction (DRR) and community resilience manuals with key messages.\nOperational Planning: Developed preparedness and response operation plans covering roles, procedures, and coordination mechanisms.\nRisk Awareness: Conducted hazard and vulnerability mapping and community sensitisation.\nResilient Design Inputs: Provided guidance for resilient shelters, water points, latrines, and community infrastructure.\nBuild Back Better: Promoted low-cost, locally available replication techniques.\nStandards Alignment: Ensured alignment with international standards and government priorities.",
        'area' => 'Jacobabad, Kashmore, Shikarpur, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Aug 2012 to Dec 2014 (29 months)',
        'title' => 'Project Implementation and M&E Consultant - Sindh Flood Resilience and Recovery Programme',
        'client' => "Concern Worldwide Pakistan (RAPID Fund)\nFunded by RAPID Fund / Concern Worldwide",
        'scope' => "Implementation Support: Developed planning frameworks, work plans, budgets, and monitoring schedules.\nCoordination: Coordinated among stakeholders and three partner NGOs.\nMonitoring: Conducted alignment checks against outputs and outcomes; documented progress.\nCapacity Support: Strengthened capacities of staff and implementing partners.\nReporting: Delivered regular project reporting and documentation.\nM&E Review: Conducted operational review of M&E framework, tools, and reporting; provided recommendations for improvements.\nTargeting & Impact: Assessed targeting mechanism efficiency and effectiveness; conducted poverty impact assessment.\nFramework Development: Strengthened M&E framework and developed indicators and tools for all components and partners.",
        'area' => 'Dadu, Naushahro Feroze, Sanghar, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Jul 2012 to Sep 2014 (27 months)',
        'title' => 'Project Design, Monitoring and Supervision Consultant - Urban Water and Sanitation for Katchi Abadis/Slums',
        'client' => "KOICA Pakistan & Public Health Engineering Department (PHED), Government of Sindh\nFunded by Korea International Cooperation Agency (KOICA)",
        'scope' => "Engineering Design: Developed designs and BOQs for solar-powered water supply, low-cost sanitation, sewerage, drainage, and solid waste management (SWM).\nConstruction Supervision: Provided quality assurance and compliance monitoring; coordinated with PHED, Local Government Department (LGD), and communities.\nSolar Water Systems: Supported installation of solar water supply systems with storage and distribution.\nSanitation Facilities: Designed low-cost sanitation solutions and public toilets with handwashing stations.\nSWM: Designed community solid waste management collection and disposal systems; developed O&M frameworks.\nCommunity Institutions: Formed and trained Village Development Committees (VDCs), gender groups, and O&M Committees; established O&M fund arrangements.\nCapacity Building/BCC: Delivered hygiene promotion, disaster risk reduction (DRR), and O&M training; implemented behaviour change communication (BCC) campaigns to improve sanitation and waste behaviours.\nM&E/Sustainability: Conducted monitoring, evaluation, and functionality assessments; developed sustainability planning and handover support.",
        'area' => 'Hyderabad & Mirpurkhas, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Mar 2012 to Feb 2014 (24 months)',
        'title' => 'Construction Monitoring and Supervision for Rehabilitation of Safe Drinking Water and Toilet Facilities in Government Primary Schools',
        'client' => 'UNICEF Pakistan',
        'scope' => "Mobilisation/Planning: Conducted kick-off and coordination meetings; reviewed drawings, specifications, BOQs, and standards; developed supervision plan, checklists, and escalation protocol; established school-wise tracking.\nWater Supply Supervision: Verified rehabilitation of pumps, bore systems, tanks, and distribution networks; ensured safety (drainage, leak-proofing, electrical where applicable); conducted commissioning and functionality checks.\nSanitation Supervision: Verified civil works, fixtures, and disposal systems (soak pits/septic/sewer), accessibility, and privacy; ensured gender-appropriate arrangements.\nQA/QC: Managed material approvals; conducted stage inspections; issued and closed non-conformance reports (NCRs) and non-conformance notices (NCNs); maintained photo logs and test records.\nHealth, Safety & Environment (HSE): Enforced PPE use; established child-safe work zones; managed waste management and housekeeping; implemented incident reporting and corrective actions.\nProgress/Payments: Verified quantities and supported interim payment certificate (IPC) and running account (RA) certification; maintained progress dashboards and risk tracking.\nCompletion/Handover: Managed snagging and rectification; verified usability; prepared handover documentation; provided orientation for routine upkeep.",
        'area' => '489 Schools, Dadu & Naushahro Feroze, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => 'Mar 2011 to May 2013 (27 months)',
        'title' => 'Operation Review and Monitoring Consultant - Hygiene Promotion in Sindh (PHAST & Child-to-Child)',
        'client' => 'ACTED',
        'scope' => "Baseline: Conducted socio-economic and WASH baseline surveys to identify hygiene barriers.\nImplementation Monitoring: Monitored two-phase hygiene promotion programme using Participatory Hygiene and Sanitation Transformation (PHAST) and Child-to-Child methodologies.\nBehaviour Change: Supported activities led by children as agents of change including presentations, community visits, quizzes, debates, hygiene competitions, and street theatre.\nInclusion: Engaged mothers and non-school-going children; facilitated community-wide participation with parents and teachers.\nMeasurement: Conducted start and end Knowledge, Attitudes, and Practices (KAP) surveys to assess behaviour change and impact.\nReporting: Documented results, lessons learned, and recommendations for programme strengthening.",
        'area' => 'Ghotki, Jacobabad, Dadu, Sindh',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
    [
        'year' => '2008 to 2011 (36 months)',
        'title' => 'Promotion of Education among Coastal Communities',
        'client' => 'Pakistan Poverty Alleviation Fund (PPAF)',
        'scope' => "Diagnostics: Surveyed 160+ schools assessing enrolment, teacher qualifications and training, facilities, and missing infrastructure.\nInfrastructure Support: Supported physical infrastructure improvements.\nTeacher Development: Delivered early childhood education (ECE) training and subject-specific training for high school teachers.\nSMC Strengthening: Trained School Management Committees (SMCs); developed and implemented School Improvement Plans.\nCommunity Engagement: Developed community engagement plan and School Ownership Manual; facilitated public complaint sessions with high female participation.\nAccess/Equity: Conducted girls' enrolment drives and community mobilisation.\nGRM: Formed Grievance Redressal Mechanism (GRM) committees in each school and provided grievance handling support.\nWASH/Environment: Developed and delivered hygiene promotion materials and sessions (IEC); established Children's Environmental Clubs.",
        'area' => 'Thatta & Badin, Sindh (160 Schools)',
        'status' => 'Completed',
        'status_key' => 'completed',
    ],
];
